// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDH9pUgRnYugDq3c2aX-9acARkxjbuYNT8',
    appId: '1:568721215732:web:416559818f606bade34ea1',
    messagingSenderId: '568721215732',
    projectId: 'portfoliobuildersite',
    authDomain: 'portfoliobuildersite.firebaseapp.com',
    storageBucket: 'portfoliobuildersite.firebasestorage.app',
    measurementId: 'G-WVJRRPRD7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqdSlphT2Qp0BdKmqpaENWvTDtasFl5n0',
    appId: '1:568721215732:android:b30796992874bf21e34ea1',
    messagingSenderId: '568721215732',
    projectId: 'portfoliobuildersite',
    storageBucket: 'portfoliobuildersite.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyTQaA0eFxTQilFIDckmHvo0fJY1pefxc',
    appId: '1:568721215732:ios:4b53e1d6ce621c97e34ea1',
    messagingSenderId: '568721215732',
    projectId: 'portfoliobuildersite',
    storageBucket: 'portfoliobuildersite.firebasestorage.app',
    androidClientId: '568721215732-0cn9o0587pflmog4f2fn8c7jg9d2oc33.apps.googleusercontent.com',
    iosClientId: '568721215732-bpi8823otiimjlfehnco7p8gv6e7jerp.apps.googleusercontent.com',
    iosBundleId: 'com.bhakundo',
  );
}
